#!/bin/sh


# always works or needs to have COMMANDS setup by distibutor?
# graph it out?
# write in Go?
#   check for pkgmngr -> ... ?


# check for xpkg? or use xbps-pkg or whatever
# xbps
if [ $(command -v xbps-install)  ]; then
    INSTALL='xbps-install -Suy'
    REMOVE='xbps-remove -Roy'
    UPDATE="xbps-install -Su"
    QUERY='xbps-query -R'
    GET_ALL='xpkg -a'
    GET_INSTALLED="$(xbps-query -m | sed 's/-[^-]*$//')"
fi

# apt
if [ $(command -v apt-get)  ]; then
    INSTALL='apt-get install -y'
    REMOVE='apt-get remove -y'
    UPDATE='apt-get update; apt-get upgrade'
    QUERY='apt-cache show'
    GET_ALL='apt-cache pkgnames'
    GET_INSTALLED='apt-mark showmanual'
fi

xi () {
    if [ "$@"  ]; then
        sudo $INSTALL "$@"
        return
    fi
    $GET_ALL |
        fzf -m --preview "$QUERY {1}" --preview-window=right:66%:wrap |
        xargs -ro sudo $INSTALL
}

xu () {
    sudo $UPDATE
}

xr () {
    if [ "$@"  ]; then
        sudo "$REMOVE" "$@"
        return
    fi
    $GET_INSTALLED |
        fzf -m --preview "$QUERY {1}" --preview-window=right:66%:wrap |
        xargs -ro sudo $REMOVE
}

