#!/bin/sh
printf 'Name:     %s\n' "$name"
printf 'Version:  %s\n' "$version"
printf 'Desc:     %s\n' "$desc"
printf 'Homepage: %s\n' "$homepage"
if [ "$installed_size" ]; then
    printf 'Size:     %s\n' "$installed_size"
fi
printf 'Arch:     %s\n' "$arch"
if [ "$license" ]; then
    printf 'License:  %s\n' "$license"
fi
printf 'Depends:  %s\n' "$depends"
