#!/bin/sh

# version defined when installing by makefile
version=dummy

version () {
    printf '%s' "$0 version $version"
}

# also defined when installing
in=xf
up=xu
rem=xr

usage="$0 $version is a multicall script (think busybox) and
behaves differently according to how it's called.

Usage: xinst [OPTION]
   or: xinst <function> [PKGS]
   or: <function> [PKGS]

If no PKGS are given, open fzf menu.

FUNCTIONS:
  $in: install PKGS
  $up: update all PKGS
  $rem: remove PKGS

OPTIONS:
  -v --version        Print version.
  -h --help           Print this text.
  -s --supported      Print list of supported package managers.
"

usage () {
    printf '%s' "$usage"
}

supported="Currently supported package managers:
+------+------------------+--------------------+
| tool | used by          | extra requirements |
+------+------------------+--------------------+
| xbps | Void Linux       | xpkg               |
| apt  | Debian GNU/Linux |                    |
+------+------------------+--------------------+
"

supported () {
    printf '%s' "$supported"
}

if [ ! "$(command -v fzf)" ]; then
    echo 'fzf not found!'
    exit 1
fi

# requires xbps and xtools
if [ "$(command -v xbps-install)" ]; then
    if [ ! "$(command -v xpkg)" ]; then
        printf 'xpkg not found!\n\tyou can install it with `# xbps-install xtools`\n'
        exit 1
    fi
    INSTALL='xbps-install -Suy'
    REMOVE='xbps-remove -Roy'
    UPDATE="xbps-install -Su"
    UPDATE_SELF="xbps-install -u xbps"
    QUERY='xbps-query -R'
    GET_ALL='xpkg -a'
    GET_INSTALLED="xpkg -m"
    PARSE_INFO="xinst_parse_xbps"
fi

# requires apt
if [ "$(command -v apt-get)"  ]; then
    INSTALL='apt-get install -y'
    REMOVE='apt-get remove -y'
    UPDATE='apt-get update'
    UPGRADE='apt-get upgrade -y'
    UPDATE_SELF='false'
    QUERY='apt-cache show'
    GET_ALL='apt-cache pkgnames'
    GET_INSTALLED='apt-mark showmanual'
    PARSE_INFO="xinst_parse_apt"
fi

if [ -z "$INSTALL" ]; then
    echo "Your package manager is not supported"
    supported
    exit 1
fi

VIEW="fzf -m --preview '$QUERY {1} | $PARSE_INFO' --preview-window=right:66%:wrap"

install () {
    if [ "$@" ]; then
        sudo $INSTALL "$@"
        return
    fi
    $GET_ALL | $VIEW | xargs -ro sudo $INSTALL
}

update () {
    # if updating fails, try updating our package manager first, then retry
    sudo $UPDATE || sudo $UPDATE_SELF || sudo $UPDATE
    if [ "$UPGRADE" ]; then
        sudo $UPGRADE
    fi
}

remove () {
    if [ "$@" ]; then
        sudo $REMOVE "$@"
        return
    fi
    $GET_INSTALLED | $VIEW | xargs -ro sudo $REMOVE
}

# execute function
case "$0" in
    *"$in") install "$@"
        ;;
    *"$up") update "$@"
        ;;
    *"$rem") remove "$@"
        ;;
    *xinst)
        case "$1" in
        "$in") shift
            install "$@"
            ;;
        "$up") shift
            update "$@"
            ;;
        "$rem") shift
            remove "$@"
            ;;
        *) usage
            exit 0
            ;;
        esac
        ;;
    *)  usage
        exit 0
        ;;
esac

# parse options
case "$1" in
    -h|--help)
        usage
        exit 0
        ;;
    -v|--version)
        version
        exit 0
        ;;
    -s|--supported)
        supported
        exit 0
        ;;
    '') ;;
    *)  echo "Unknown option '$1'"
        usage
        exit 0
        ;;
esac

# unset defined functions
unset install update remove usage supported version
